server:
  port: 8095

mybatis:
  mapper-locations:
    - "classpath*:/sql/mappers/*/*Mapper.xml"
    - "classpath*:/sql/mappers/*Mapper.xml"
  config-location: classpath:mybatis-config.xml

spring:
  datasource:
    url: jdbc:postgresql://john.db.elephantsql.com/rkkzalcv
    username: rkkzalcv
    password: yqHuj7YNdd9yNDE4wwhSItFNRdRaV9C1
    driverClassName: org.postgresql.Driver

jwt:
  secret_key: 5A7134743777397A24432646294A404635266556A5863272357538782F4125
  life_time_in_hours: 24

user:
  default_password_expire_days: 90